/**
 * CoreMeta4Cat configuration
 *
 * Schema: compiled from schemas/coremeta4cat/schema/coremeta4cat.yaml
 * The compiled JSON schema is generated by the CI pipeline (deploy.yml)
 * and placed at src/schema/coremeta4cat.schema.json.
 *
 * For local development, replace the placeholder schema with:
 *   pip install linkml
 *   gen-json-schema schemas/coremeta4cat/schema/coremeta4cat.yaml \
 *     > src/schema/coremeta4cat.schema.json
 */
import schema   from '../schema/coremeta4cat.schema.json';
import rxnJson  from '../examples/coremeta4cat/Reaction-001.json';
import synthJson from '../examples/coremeta4cat/Synthesis-001.json';
import dsJson   from '../examples/coremeta4cat/CatalysisDataset-001.json';

// ── Abstract / infrastructure classes to hide from the node palette ──────────
// gen-json-schema does NOT emit `abstract: true`, so we list them explicitly.
// DCAT-AP+ base hierarchy (shared infrastructure, never directly instantiated):
const DCAT_AP_BASE = [
  'Activity', 'Agent', 'AgenticEntity',
  'DataGeneratingActivity',
  'Entity', 'EvaluatedActivity', 'EvaluatedEntity',
  'Kind', 'Plan',
];
// DCAT catalog / administrative infrastructure (not catalysis domain nodes):
const DCAT_ADMIN = [
  'Catalogue', 'CatalogueRecord', 'Checksum',
  'DataService', 'DatasetSeries',
  'Distribution', 'LicenseDocument',
  'PeriodOfTime', 'Relationship',
];
// CoreMeta4Cat-specific abstract base classes (abstract: true in source YAML):
const COREMETA_ABSTRACT = [
  'CharacterizationTechnique', // abstract base → concrete techniques (XRD, BET, etc.)
  'PreparationMethod',          // abstract base → Impregnation, CoPrecipitation, etc.
  'ReactorDesignType',          // abstract base → FixedBedReactor, etc.
  'SimulationMethod',           // abstract base → DFT, MolecularDynamics, etc.
  'CalculatedProperty',         // abstract base → ThermodynamicStability, etc.
  // DCAT-AP+ material/entity abstract bases:
  'Device',                     // abstract AgenticEntity base
  'MaterialEntity',             // abstract material base
  'ChemicalEntity',             // abstract chemical entity base
];

export const config = {
  appTitle:    'Schema Graph Editor',
  appSubtitle: 'CoreMeta4Cat visual instance editor',
  githubUrl:   'https://github.com/nfdi4cat/CoreMeta4Cat',
  schema,
  abstractClasses: [...DCAT_AP_BASE, ...DCAT_ADMIN, ...COREMETA_ABSTRACT],
  examples: [
    {
      json:  rxnJson,
      label: 'Reaction',
      title: 'CO₂ Hydrogenation',
      desc:  'Heterogeneous catalytic CO₂ hydrogenation in a fixed-bed plug-flow reactor.',
    },
    {
      json:  synthJson,
      label: 'Synthesis',
      title: 'Pt/Al₂O₃ Catalyst',
      desc:  'Incipient wetness impregnation synthesis of a supported platinum catalyst.',
    },
    {
      json:  dsJson,
      label: 'CatalysisDataset',
      title: 'MeOH Synthesis Dataset',
      desc:  'Cu/ZnO/Al₂O₃ methanol synthesis — performance and preparation metadata.',
    },
  ],
};
