/**
 * CoreMeta4Cat configuration
 *
 * Schema: compiled from schemas/coremeta4cat/schema/coremeta4cat.yaml
 * The compiled JSON schema is generated by the CI pipeline (deploy.yml)
 * and placed at src/schema/coremeta4cat.schema.json.
 *
 * For local development, replace the placeholder schema with:
 *   pip install linkml
 *   gen-json-schema schemas/coremeta4cat/schema/coremeta4cat.yaml \
 *     > src/schema/coremeta4cat.schema.json
 */
import schema   from '../schema/coremeta4cat.schema.json';
import rxnJson  from '../examples/coremeta4cat/Reaction-001.json';
import synthJson from '../examples/coremeta4cat/Synthesis-001.json';
import dsJson   from '../examples/coremeta4cat/CatalysisDataset-001.json';

export const config = {
  appTitle:    'Schema Graph Editor',
  appSubtitle: 'CoreMeta4Cat visual instance editor',
  githubUrl:   'https://github.com/nfdi4cat/CoreMeta4Cat',
  schema,
  examples: [
    {
      json:  rxnJson,
      label: 'Reaction',
      title: 'CO₂ Hydrogenation',
      desc:  'Heterogeneous catalytic CO₂ hydrogenation in a fixed-bed plug-flow reactor.',
    },
    {
      json:  synthJson,
      label: 'Synthesis',
      title: 'Pt/Al₂O₃ Catalyst',
      desc:  'Incipient wetness impregnation synthesis of a supported platinum catalyst.',
    },
    {
      json:  dsJson,
      label: 'CatalysisDataset',
      title: 'MeOH Synthesis Dataset',
      desc:  'Cu/ZnO/Al₂O₃ methanol synthesis — performance and preparation metadata.',
    },
  ],
};
