/**
 * CoreMeta4Cat configuration
 *
 * Schema: compiled from schemas/coremeta4cat/schema/coremeta4cat.yaml
 * The compiled JSON schema is generated by the CI pipeline (deploy.yml)
 * and placed at src/schema/coremeta4cat.schema.json.
 *
 * For local development, replace the placeholder schema with:
 *   pip install linkml
 *   gen-json-schema schemas/coremeta4cat/schema/coremeta4cat.yaml \
 *     > src/schema/coremeta4cat.schema.json
 */
import schema   from '../schema/coremeta4cat.schema.json';
import rxnJson  from '../examples/coremeta4cat/Reaction-001.json';
import synthJson from '../examples/coremeta4cat/Synthesis-001.json';
import dsJson   from '../examples/coremeta4cat/CatalysisDataset-001.json';

// Raw YAML sources for schema template viewer (inheritance map extraction)
import yaml_main          from '../../schemas/coremeta4cat/schema/coremeta4cat.yaml?raw';
import yaml_common        from '../../schemas/coremeta4cat/schema/coremeta4cat_common.yaml?raw';
import yaml_synthesis     from '../../schemas/coremeta4cat/schema/coremeta4cat_synthesis_ap.yaml?raw';
import yaml_char          from '../../schemas/coremeta4cat/schema/coremeta4cat_characterization_ap.yaml?raw';
import yaml_reaction      from '../../schemas/coremeta4cat/schema/coremeta4cat_reaction_ap.yaml?raw';
import yaml_simulation    from '../../schemas/coremeta4cat/schema/coremeta4cat_simulation_ap.yaml?raw';
import yaml_chem_dcat_ap  from '../../schemas/coremeta4cat/schema/chem_dcat_ap.yaml?raw';
import yaml_material      from '../../schemas/coremeta4cat/schema/material_entities_ap.yaml?raw';
import yaml_chemical      from '../../schemas/coremeta4cat/schema/chemical_entities_ap.yaml?raw';
import yaml_chem_rxn      from '../../schemas/coremeta4cat/schema/chemical_reaction_ap.yaml?raw';
import yaml_dcat4c        from '../../schemas/coremeta4cat/schema/dcat_4c_ap.yaml?raw';

// ── Abstract / infrastructure classes to hide from the node palette ──────────
// gen-json-schema does NOT emit `abstract: true`, so we list them explicitly.
// DCAT-AP+ base hierarchy (shared infrastructure, never directly instantiated):
const DCAT_AP_BASE = [
  'Activity', 'Agent', 'AgenticEntity',
  'DataGeneratingActivity',
  'Entity', 'EvaluatedActivity', 'EvaluatedEntity',
  'Kind', 'Plan',
];
// DCAT catalog / administrative infrastructure (not catalysis domain nodes):
const DCAT_ADMIN = [
  'Catalogue', 'CatalogueRecord', 'Checksum',
  'DataService', 'DatasetSeries',
  'Distribution', 'LicenseDocument',
  'PeriodOfTime', 'Relationship',
];
// CoreMeta4Cat-specific abstract base classes (abstract: true in source YAML):
const COREMETA_ABSTRACT = [
  'CharacterizationTechnique', // abstract base → concrete techniques (XRD, BET, etc.)
  'PreparationMethod',          // abstract base → Impregnation, CoPrecipitation, etc.
  'ReactorDesignType',          // abstract base → FixedBedReactor, etc.
  'SimulationMethod',           // abstract base → DFT, MolecularDynamics, etc.
  'CalculatedProperty',         // abstract base → ThermodynamicStability, etc.
  // DCAT-AP+ material/entity abstract bases:
  'Device',                     // abstract AgenticEntity base
  'MaterialEntity',             // abstract material base
  'ChemicalEntity',             // abstract chemical entity base
];
// DCAT-AP / DCAT-AP+ data-catalog classes that should never be auto-inferred
// as children of domain slots. They have 39 properties (the most in the schema)
// and would win every tie-break, incorrectly appearing as children of material
// or activity nodes. Excluded from inference; still usable via explicit @type.
const DCAT_DATA_CLASSES = [
  'AnalysisDataset',                       // dataset catalog entity, not a domain node
  'CatalysisDataset',                      // coremeta4cat dataset root, not a domain child node
  'Dataset',                               // base DCAT-AP dataset
  'ReactionMonitoringDataset',             // dataset subtype — root class only, not an inferred child
  'SubstanceSampleCharacterizationDataset', // dataset subtype — root class only, not an inferred child
];

export const config = {
  appTitle:    'Schema Graph Editor',
  appSubtitle: 'CoreMeta4Cat visual instance editor',
  githubUrl:   'https://github.com/nfdi4cat/CoreMeta4Cat',
  schemaId:    'coremeta4cat',
  schema,
  yamlSources: [yaml_main, yaml_common, yaml_synthesis, yaml_char, yaml_reaction, yaml_simulation, yaml_chem_dcat_ap, yaml_material, yaml_chemical, yaml_chem_rxn, yaml_dcat4c],
  abstractClasses: [...DCAT_AP_BASE, ...DCAT_ADMIN, ...COREMETA_ABSTRACT, ...DCAT_DATA_CLASSES],
  examples: [
    {
      json:  rxnJson,
      label: 'Reaction',
      title: 'CO₂ Hydrogenation',
      desc:  'Heterogeneous catalytic CO₂ hydrogenation in a fixed-bed plug-flow reactor.',
    },
    {
      json:  synthJson,
      label: 'Synthesis',
      title: 'Pt/Al₂O₃ Catalyst',
      desc:  'Incipient wetness impregnation synthesis of a supported platinum catalyst.',
    },
    {
      json:  dsJson,
      label: 'CatalysisDataset',
      title: 'MeOH Synthesis Dataset',
      desc:  'Cu/ZnO/Al₂O₃ methanol synthesis — performance and preparation metadata.',
    },
  ],
};
