/**
 * DCAT-AP+ configuration
 *
 * Schema: compiled from schemas/dcat_ap_plus/schema/dcat_ap_plus.yaml
 * The compiled JSON schema is generated by the CI pipeline (deploy.yml)
 * and placed at src/schema/dcat_ap_plus.schema.json.
 *
 * For local development, replace the placeholder schema with:
 *   pip install linkml
 *   gen-json-schema schemas/dcat_ap_plus/schema/dcat_ap_plus.yaml \
 *     > src/schema/dcat_ap_plus.schema.json
 */
import schema   from '../schema/dcat_ap_plus.schema.json';
import dsJson   from '../examples/dcat-ap-plus/Dataset-001.json';
import adsJson  from '../examples/dcat-ap-plus/AnalysisDataset-001.json';

// Raw YAML sources for schema template viewer (inheritance map extraction)
import yaml_dcat_ap_plus from '../../schemas/dcat_ap_plus/schema/dcat_ap_plus.yaml?raw';
import yaml_dcat_linkml  from '../../schemas/dcat_ap_plus/schema/dcat_ap_linkml.yaml?raw';

// ── Abstract / infrastructure classes to hide from the node palette ──────────
// gen-json-schema does NOT emit `abstract: true`, so we list them explicitly.
// DCAT-AP+ base hierarchy (shared infrastructure, never directly instantiated):
const DCAT_AP_ABSTRACT = [
  'Activity', 'Agent', 'AgenticEntity',
  'DataGeneratingActivity',
  'Entity', 'EvaluatedActivity', 'EvaluatedEntity',
  'Kind', 'Plan',
];

export const config = {
  appTitle:    'Schema Graph Editor',
  appSubtitle: 'DCAT-AP+ visual instance editor',
  githubUrl:   'https://github.com/nfdi-de/dcat-ap-plus',
  schemaId:    'dcat-ap-plus',
  schema,
  yamlSources: [yaml_dcat_ap_plus, yaml_dcat_linkml],
  abstractClasses: [...DCAT_AP_ABSTRACT],
  examples: [
    {
      json:  dsJson,
      label: 'Dataset',
      title: '13C NMR Dataset',
      desc:  'Generic DCAT-AP+ dataset describing a 13C NMR spectroscopy result.',
    },
    {
      json:  adsJson,
      label: 'AnalysisDataset',
      title: 'NMR Analysis Dataset',
      desc:  'Analysis dataset linking NMR spectra with compound identification and molar mass.',
    },
  ],
};
