/**
 * DCAT-AP+ configuration
 *
 * Schema: compiled from schemas/dcat_ap_plus/schema/dcat_ap_plus.yaml
 * The compiled JSON schema is generated by the CI pipeline (deploy.yml)
 * and placed at src/schema/dcat_ap_plus.schema.json.
 *
 * For local development, replace the placeholder schema with:
 *   pip install linkml
 *   gen-json-schema schemas/dcat_ap_plus/schema/dcat_ap_plus.yaml \
 *     > src/schema/dcat_ap_plus.schema.json
 */
import schema   from '../schema/dcat_ap_plus.schema.json';
import dsJson   from '../examples/dcat-ap-plus/Dataset-001.json';
import adsJson  from '../examples/dcat-ap-plus/AnalysisDataset-001.json';

export const config = {
  appTitle:    'Schema Graph Editor',
  appSubtitle: 'DCAT-AP+ visual instance editor',
  githubUrl:   'https://github.com/nfdi-de/dcat-ap-plus',
  schema,
  examples: [
    {
      json:  dsJson,
      label: 'Dataset',
      title: '13C NMR Dataset',
      desc:  'Generic DCAT-AP+ dataset describing a 13C NMR spectroscopy result.',
    },
    {
      json:  adsJson,
      label: 'AnalysisDataset',
      title: 'NMR Analysis Dataset',
      desc:  'Analysis dataset linking NMR spectra with compound identification and molar mass.',
    },
  ],
};
